name: Run Script Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # This cron expression means "at minute 0 of every hour"
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create profile.json from secret
      run: |
        echo "${{ secrets.PROFILES_JSON }}" | jq '.' > profiles.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the script
      run: python app.py